//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldenPersonelYonetimi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class userManagementEntities : DbContext
    {
        public userManagementEntities()
            : base("name=userManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Departman> Departman { get; set; }
    
        public virtual ObjectResult<PersonelListesi_Result2> PersonelListesi(Nullable<int> onlu)
        {
            var onluParameter = onlu.HasValue ?
                new ObjectParameter("onlu", onlu) :
                new ObjectParameter("onlu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PersonelListesi_Result2>("PersonelListesi", onluParameter);
        }
    
        public virtual ObjectResult<kullCek_Result> kullCek(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<kullCek_Result>("kullCek", idParameter);
        }
    }
}
